table Customer
	lineageTag: a1b2c3d4-0002-4000-8000-000000000001

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: a1b2c3d4-0002-4000-8000-000000000020
		summarizeBy: none
		sourceColumn: CustomerID

	column CustomerName
		dataType: string
		lineageTag: a1b2c3d4-0002-4000-8000-000000000021
		summarizeBy: none
		sourceColumn: CustomerName

	column Region
		dataType: string
		lineageTag: a1b2c3d4-0002-4000-8000-000000000022
		summarizeBy: none
		sourceColumn: Region

	partition Customer = m
		mode: import
		source =
				let
					Source = Table.FromRows(
							{
								{1, "Contoso Retail", "West"},
								{2, "Fabrikam Inc", "East"},
								{3, "Northwind Traders", "West"},
								{4, "Tailspin Toys", "Central"},
								{5, "Adventure Works", "East"}
							},
							{"CustomerID", "CustomerName", "Region"}
						),
					ChangedType = Table.TransformColumnTypes(
							Source,
							{
								{"CustomerID", Int64.Type},
								{"CustomerName", type text},
								{"Region", type text}
							}
						)
				in
					ChangedType

	annotation PBI_ResultType = Table

